name: fieldsnap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  image_picker: ^1.2.1
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6
  logger: ^2.6.2
  lottie: ^3.3.1
  cached_network_image: ^3.3.1
  get: ^4.6.6
  dio: ^5.7.0
  camera: ^0.11.3
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  app_settings: ^7.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android: true
  ios: true

flutter_launcher_icons:
  image_path: assets/logo.png
  android: true
  ios: true
  remove_alpha_ios: true
